### ISSUE TITLE
I want to increase the defaults for signature algorithm.

### ISSUE THREAD

**Issue by nannany** [zitadel/oidc#605] opened 2024-05-07 15:23 UTC
### Preflight Checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions
- [X] I have joined the [ZITADEL chat](https://zitadel.com/chat)

### Describe your problem

I am using zitadel/oidc to create an OpenID Provider.
I believe the library intends that the [VerifyJWTAssertion](https://github.com/zitadel/oidc/blob/33f8df7eb28f19fd27ffd8ad12390b3cc74a247a/pkg/op/verifier_jwt_profile.go#L66) function is called when client authentication is done with private_key_jwt.
However, this function currently only supports RS256 since the [supportedSigAlgs](https://github.com/zitadel/oidc/blob/33f8df7eb28f19fd27ffd8ad12390b3cc74a247a/pkg/op/verifier_jwt_profile.go#L96) argument is nil when executing the CheckSignature function.
Therefore I would like to sign with ES256, which is not possible.

### Describe your ideal solution

Since the [FAPI](https://openid.net/specs/openid-financial-api-part-2-ID2.html#jws-algorithm-considerations) states that PS256 or ES256 is recommended, why not support PS256 or ES256 if it is not specified here as well? 

### Version

v3.22.1

### Environment

Self-hosted

**Comment by hifabienne** [comment] 2024-05-15 07:56
I think this is a duplicate of the following issue? https://github.com/zitadel/oidc/issues/259
@muhlemmer @livio-a am I right? In that case I would close the issue here, to avoid duplicates

**Comment by muhlemmer** [comment] 2024-05-17 10:18
closed by https://github.com/zitadel/oidc/pull/606

**Closed by muhlemmer** 2024-05-17 10:18 UTC
Labels: improvement, auth
